# Generated by Django 3.0.6 on 2020-06-03 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal_Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('colorval_nav_bar', models.CharField(blank=True, default='', max_length=7)),
                ('colorval_heading', models.CharField(blank=True, default='', max_length=7)),
                ('colorval_text', models.CharField(blank=True, default='', max_length=7)),
                ('colorval_button', models.CharField(blank=True, default='', max_length=7)),
                ('colorval_zurueck_button', models.CharField(blank=True, default='', max_length=7)),
                ('institute_logo', models.ImageField(blank=True, default='static/Tu-ilmenauLogo.png', upload_to='images')),
                ('krankenkasse_logo', models.ImageField(blank=True, default='static/Logo_AOK_PLUS.svg.png', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=100)),
                ('menu_text', models.TextField(blank=True)),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='self_service_terminal.Menu')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='self_service_terminal.Terminal_Settings')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdffile', models.FileField(blank=True, null=True, upload_to='forms')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('show_on_frontend', models.BooleanField(default=False)),
                ('form_title', models.CharField(default='Formular', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('parent_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='self_service_terminal.Menu')),
            ],
        ),
    ]
