# Generated by Django 3.0.6 on 2020-05-25 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorval', models.PositiveIntegerField()),
                ('institute_logo', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Startpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_title', models.CharField(max_length=100)),
                ('start_text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='form_title',
            field=models.CharField(default='Formular', max_length=120),
        ),
        migrations.AddField(
            model_name='form',
            name='pdffile',
            field=models.FileField(blank=True, null=True, upload_to='forms'),
        ),
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='show_on_frontend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=100)),
                ('menu_text', models.TextField(blank=True)),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='self_service_terminal.Menu')),
                ('startpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='self_service_terminal.Startpage')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='parent_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='self_service_terminal.Menu'),
        ),
    ]
