# Generated by Django 3.0.5 on 2020-06-03 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal_Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_title', models.CharField(max_length=100)),
                ('start_text', models.TextField()),
                ('colorval_nav_bar', models.CharField(blank=True, default='', max_length=7)),
                ('colorval_heading', models.CharField(blank=True, default='', max_length=7)),
                ('colorval_text', models.CharField(blank=True, default='', max_length=7)),
                ('colorval_button', models.CharField(blank=True, default='', max_length=7)),
                ('colorval_zurueck_button', models.CharField(blank=True, default='', max_length=7)),
                ('institute_logo', models.ImageField(blank=True, default='static/Tu-ilmenauLogo.png', upload_to='images')),
                ('krankenkasse_logo', models.ImageField(blank=True, default='static/Logo_AOK_PLUS.svg.png', upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='form_title',
            field=models.CharField(default='Formular', max_length=100),
        ),
        migrations.AddField(
            model_name='form',
            name='pdffile',
            field=models.FileField(blank=True, null=True, upload_to='forms'),
        ),
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='show_on_frontend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=100)),
                ('menu_text', models.TextField(blank=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='self_service_terminal.Terminal_Settings')),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='self_service_terminal.Menu')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='parent_menu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='self_service_terminal.Menu'),
            preserve_default=False,
        ),
    ]
