# Generated by Django 3.0.6 on 2020-05-25 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0002_auto_20200525_1552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Startpage',
            new_name='Homepage',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='startpage',
            new_name='homepage',
        ),
        migrations.AddField(
            model_name='form',
            name='homepage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='self_service_terminal.Homepage'),
        ),
    ]
