# Generated by Django 3.0.5 on 2020-06-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0002_terminal_settings_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='test_img',
            field=models.ImageField(blank=True, default='default.png', upload_to='images'),
        ),
    ]
