# Generated by Django 3.0.6 on 2020-05-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0003_auto_20200525_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Design',
        ),
        migrations.RemoveField(
            model_name='form',
            name='homepage',
        ),
        migrations.AddField(
            model_name='form',
            name='colorval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='institute_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='colorval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='institute_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='menu',
            name='colorval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='institute_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
