# Generated by Django 3.0.5 on 2020-06-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0003_menu_test_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_texttt',
            field=models.TextField(blank=True),
        ),
    ]
