# Generated by Django 3.0.5 on 2020-06-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0004_menu_menu_texttt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_texttt',
        ),
    ]
