# Generated by Django 3.0.6 on 2020-05-25 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0004_auto_20200525_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='colorval',
        ),
        migrations.RemoveField(
            model_name='form',
            name='institute_logo',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='colorval',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='institute_logo',
        ),
        migrations.AlterField(
            model_name='menu',
            name='homepage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='self_service_terminal.Homepage'),
        ),
    ]
