# Generated by Django 3.0.6 on 2020-06-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0005_remove_menu_menu_texttt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='test_img',
        ),
    ]
