# Generated by Django 3.0.6 on 2020-05-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0005_auto_20200525_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='parent_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='self_service_terminal.Menu'),
        ),
    ]
