# Generated by Django 3.0.6 on 2020-06-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0006_remove_menu_test_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminal_settings',
            old_name='krankenkasse_logo',
            new_name='insurance_logo',
        ),
    ]
