# Generated by Django 3.0.6 on 2020-05-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0006_auto_20200525_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form_title',
            field=models.CharField(default='Formular', max_length=100),
        ),
    ]
