# Generated by Django 3.0.6 on 2020-05-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0006_auto_20200525_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homepage',
            new_name='Terminal_Settings',
        ),
        migrations.AlterField(
            model_name='form',
            name='form_title',
            field=models.CharField(default='Formular', max_length=100),
        ),
    ]
