# Generated by Django 3.0.6 on 2020-06-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0007_auto_20200529_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal_settings',
            name='colorval',
            field=models.CharField(default=0, max_length=7),
        ),
    ]
