# Generated by Django 3.0.5 on 2020-06-30 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0008_auto_20200611_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='pdffile',
            field=models.FileField(default='forms/default.pdf', upload_to='forms'),
        ),
    ]
