# Generated by Django 3.0.6 on 2020-06-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0008_auto_20200611_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='pdffile',
            field=models.FileField(default='forms/default.pdf', upload_to='forms'),
        ),
    ]
