# Generated by Django 3.0.5 on 2020-06-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0009_auto_20200630_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='font_size',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
