# Generated by Django 3.0.5 on 2020-06-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0008_auto_20200601_1249'),
        ('self_service_terminal', '0009_auto_20200601_1316'),
    ]

    operations = [
    ]
