# Generated by Django 3.0.6 on 2020-06-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0010_auto_20200613_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal_settings',
            name='institute_logo',
            field=models.ImageField(default='Tu-ilmenauLogo.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='terminal_settings',
            name='insurance_logo',
            field=models.ImageField(default='Logo_AOK_PLUS.svg.png', upload_to='images'),
        ),
    ]
