# Generated by Django 3.0.5 on 2020-06-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0011_auto_20200601_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal_settings',
            name='institute_logo',
            field=models.ImageField(blank=True, default='images/placeholder.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='terminal_settings',
            name='krankenkasse_logo',
            field=models.ImageField(blank=True, default='images/placeholder.jpg', null=True, upload_to='images'),
        ),
    ]
