# Generated by Django 3.0.6 on 2020-06-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0011_auto_20200613_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal_settings',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terminal_settings',
            name='institute_logo',
            field=models.ImageField(default='images/institute_logo.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='terminal_settings',
            name='insurance_logo',
            field=models.ImageField(default='images/insurance_logo.png', upload_to='images'),
        ),
    ]
