# Generated by Django 3.0.6 on 2020-06-19 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0012_auto_20200613_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='settings',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='self_service_terminal.Terminal_Settings'),
        ),
    ]
