# Generated by Django 3.0.6 on 2020-06-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0013_auto_20200619_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='settings',
            field=models.ForeignKey(blank=True, default='settings', null=True, on_delete=django.db.models.deletion.CASCADE, to='self_service_terminal.Terminal_Settings', to_field='title'),
        ),
        migrations.AlterField(
            model_name='terminal_settings',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
