# Generated by Django 3.0.5 on 2020-06-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0013_auto_20200602_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminal_settings',
            old_name='colorval',
            new_name='colorval_button',
        ),
        migrations.AddField(
            model_name='terminal_settings',
            name='colorval_heading',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='terminal_settings',
            name='colorval_nav_bar',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='terminal_settings',
            name='colorval_text',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='terminal_settings',
            name='colorval_zueruck_button',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
