# Generated by Django 3.0.6 on 2020-06-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0014_auto_20200619_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminal_settings',
            old_name='colorval_zurueck_button',
            new_name='colorval_return_button',
        ),
    ]
