# Generated by Django 3.0.6 on 2020-06-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0014_auto_20200602_1218'),
        ('self_service_terminal', '0011_auto_20200602_1505'),
    ]

    operations = [
    ]
