# Generated by Django 3.0.6 on 2020-06-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0015_merge_20200602_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminal_settings',
            old_name='colorval_zueruck_button',
            new_name='colorval_zurueck_button',
        ),
        migrations.AlterField(
            model_name='terminal_settings',
            name='krankenkasse_logo',
            field=models.ImageField(blank=True, default='static/Logo_AOK_PLUS.svg.png', upload_to='images'),
        ),
    ]
