# Generated by Django 3.0.6 on 2020-06-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0015_auto_20200630_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='settings',
        ),
    ]
