# Generated by Django 3.0.6 on 2020-06-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0016_auto_20200602_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='homepage',
            new_name='settings',
        ),
    ]
