# Generated by Django 3.0.6 on 2020-06-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0016_remove_menu_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal_settings',
            name='homepage',
        ),
    ]
