# Generated by Django 3.0.6 on 2020-06-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0017_auto_20200603_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminal_settings',
            old_name='start_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='terminal_settings',
            old_name='start_title',
            new_name='title',
        ),
    ]
