# Generated by Django 3.0.6 on 2020-07-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_service_terminal', '0017_remove_terminal_settings_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'Formular', 'verbose_name_plural': 'Formulare'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menü', 'verbose_name_plural': 'Menüs'},
        ),
        migrations.AlterModelOptions(
            name='terminal_settings',
            options={'verbose_name': 'Einstellungen', 'verbose_name_plural': 'Einstellungen'},
        ),
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_title',
            field=models.CharField(default='Formular', max_length=100, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='form',
            name='last_changed',
            field=models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert'),
        ),
        migrations.AlterField(
            model_name='form',
            name='parent_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='self_service_terminal.Menu', verbose_name='Eltern-Menü'),
        ),
        migrations.AlterField(
            model_name='form',
            name='pdffile',
            field=models.FileField(default='forms/default.pdf', upload_to='forms', verbose_name='PDF-Datei'),
        ),
        migrations.AlterField(
            model_name='form',
            name='show_on_frontend',
            field=models.BooleanField(default=False, verbose_name='Im Frontend anzeigen'),
        ),
        migrations.AlterField(
            model_name='form',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaddatum'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_text',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_title',
            field=models.CharField(max_length=100, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='self_service_terminal.Menu', verbose_name='Eltern-Menü'),
        ),
        migrations.AlterField(
            model_name='terminal_settings',
            name='colorval_button',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Farbe der Buttons'),
        ),
        migrations.AlterField(
            model_name='terminal_settings',
            name='colorval_heading',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Farbe der Überschriften'),
        ),
        migrations.AlterField(
            model_name='terminal_settings',
            name='colorval_nav_bar',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Farbe der Kopfleiste'),
        ),
        migrations.AlterField(
            model_name='terminal_settings',
            name='colorval_return_button',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Farbe des Zurück-Buttons'),
        ),
        migrations.AlterField(
            model_name='terminal_settings',
            name='colorval_text',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Farbe der Texte'),
        ),
        migrations.AlterField(
            model_name='terminal_settings',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='terminal_settings',
            name='institute_logo',
            field=models.ImageField(default='images/institute_logo.png', upload_to='images', verbose_name='Institutslogo'),
        ),
        migrations.AlterField(
            model_name='terminal_settings',
            name='insurance_logo',
            field=models.ImageField(default='images/insurance_logo.png', upload_to='images', verbose_name='Krankenkassenlogo'),
        ),
        migrations.AlterField(
            model_name='terminal_settings',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Titel'),
        ),
    ]
